### ISSUE TITLE
Is there a way to scrape in this format?

### ISSUE THREAD

**Issue by NX115** [Varelion/Npower_Cloud_Study_Flashcards#3]
`[
	{
		"question": "Sample question lorem ipsum?",
		"correctAnswersArray": [
			"Sample answerlorem ipsum", 
			"another possible answer, as you can have many, lorem ipsum"
		],
		"wrongAnswersArray": [
			"Sample wrong question lorem ipsum",
			"Sample wrong question lorem ipsum",
			"Sample wrong question lorem ipsum"
		]
	},
]`

However, this will change to include additional fields when you export it, based on the difficulty rating you give a question, the notes, or hints you type down to help cement topics and clarifications. Always export your file, and save it as a `whatever_file_name.json`, and then CTRL+A, CTRL+C to copy all the content, and paste it into the importer with CTRL+V.

_Originally posted by @Varelion in https://github.com/Varelion/Npower_Cloud_Study_Flashcards/discussions/2#discussioncomment-11612097_

**Comment by Varelion** [comment]
Message me on Discord @NX115 , and I'll pass you file .js.

**Comment by Varelion** [comment]
Closing.
